config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'

  post 'create_company', to: 'pages#create_company' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees
  has_many :departments
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :company, :optional => true
  has_and_belongs_to_many :employees
end

app/models/departments_employees.rb
class DepartmentsEmployees < ApplicationRecord
  belongs_to :department
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company, :optional => true
  has_and_belongs_to_many :departments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @companies = Company.all
    @departments = Department.all
    @department_count = Department.count
  end

  def create_company
    FactoryBot.create :company
    redirect_to :root
  end

  def count_department
    
    redirect_to :root
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Is this working?</h1>

  <%= link_to "Employee with one department" %>
  <%= link_to "Employee with two departments" %>
  <%= link_to "Employee with no departments" %>

  <%= link_to "Company", create_company_path, method: :post %>

  <p><% @companies.each do |company|%>

    <li> <%= company.company_name %> <li>

  <% end %></p>